---
- name: RouterOS test with network_cli connection
  hosts: R2
  gather_facts: false
  tasks:
  - name: Configure interface loopback on R2
    cisco.ios.ios_config:
      lines:
      - description test interface
      - ip address 2.2.2.2 255.255.255.255
      parents: interface l0

  - name: Enable routing OSPF
    cisco.ios.ios_config:
      lines:
        - network 0.0.0.0 0.0.0.0 area 0
      parents: router ospf 1

